import 'core-js/modules/es.map.get-or-insert-computed';
import 'core-js/modules/es.math.sum-precise';
import 'core-js/modules/es.promise.try';
import 'core-js/modules/es.promise.with-resolvers';
import 'core-js/modules/es.regexp.escape';
import 'core-js/modules/es.uint8-array.from-base64';
import 'core-js/modules/es.uint8-array.to-base64';
import 'core-js/modules/es.uint8-array.to-hex';
import 'core-js/modules/web.url.parse';
