// Build information - This file is auto-generated and should not be tracked in git
// Generated by update-build-id.js during the build process

window.NG2_PDF_VIEWER_BUILD_ID = '2025-09-06T22-52-15-000Z';